apiVersion: v1
kind: ServiceAccount
metadata:
  name: jaeger
  labels:
    component: jaeger
    app.kubernetes.io/component: service-account
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/part-of: jaeger