---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-state-metrics


---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-state-metrics
rules:
- apiGroups: [ "" ]
  resources:
  - pods
  verbs:
  - get
- apiGroups: [ "extensions" ]
  resourceNames:
  - kube-state-metrics
  resources:
  - deployments
  verbs:
  - get
  - update
- apiGroups: [ "apps" ]
  resourceNames:
  - kube-state-metrics
  resources:
  - deployments
  verbs:
  - get
  - update


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-state-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-state-metrics
subjects:
- kind: ServiceAccount
  name: kube-state-metrics