apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-controlplane
  namespace: istio-system
spec:
  profile: demo
  namespace: istio-system

  meshConfig:
    enableTracing: true
    enablePrometheusMerge: true
    enableAutoMtls: false
    defaultConfig:
      #controlPlaneAuthPolicy: NONE
      tracing:
        openCensusAgent:
          address: dns:jaeger-collector.istio-system.svc.cluster.local:55678
          context: [ "W3C_TRACE_CONTEXT", "B3" ]
      sds:
        enabled: true


  components:
    base:
      enabled: true
      # k8s:
      #   overlays:
      #   - apiVersion: ''
      #     kind: ''
      #     name: ''
      #     patches:
      #     - path: ''
      #       value: ''
    pilot:
      enabled: true
      k8s:
        replicaCount: 1
        env:
        - name: PILOT_TRACE_SAMPLING
          value: '100.0'
        - name: PILOT_ENABLE_REDIS_FILTER
          value: 'false'
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
        hpaSpec:
          minReplicas: 1
          maxReplicas: 1

    ingressGateways:
    - name: istio-ingressgateway
      namespace: istio-system
      enabled: true
      k8s:
        replicaCount: 1
        service:
          ports:
          - name: http
            port: 80
            targetPort: 8000
          - name: https
            port: 443
            targetPort: 4443
          - name: bolt
            port: 7687
            targetPort: 7687
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
        hpaSpec:
          minReplicas: 1
          maxReplicas: 1

    egressGateways:
    - name: istio-egressgateway
      enabled: false

