apiVersion: v1
kind: ConfigMap
metadata:
  name: linkerd-collector-config
  namespace: linkerd
  labels:
    linkerd.io/control-plane-component: linkerd-collector
    linkerd.io/control-plane-ns: linkerd
  annotations:
    linkerd.io/created-by: linkerd/cli stable-2.8.1
data:
  linkerd-collector-config: |
    receivers:
      opencensus:
        port: 55678
      zipkin:
        port: 9411
    exporters:
      opencensus:
        endpoint: jaeger-collector.monitoring.svc.cluster.local:55678
        compression: gzip
