apiVersion: v1
kind: ConfigMap
metadata:
  name: linkerd-collector-config
data:
  linkerd-collector-config: |
    receivers:
      opencensus:
        port: 55678
      zipkin:
        port: 9411
    exporters:
      opencensus:
        endpoint: jaeger-collector.monitoring.svc.cluster.local:55678
        compression: gzip
