---
$patch: delete
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkerd-jaeger
  namespace: linkerd

---
$patch: delete
apiVersion: v1
kind: Service
metadata:
  name: linkerd-jaeger
  namespace: linkerd

