receivers:
  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:
  opencensus:

processors:
  batch:
    timeout: 5s
    send_batch_size: 128

service:
  pipelines:
    traces:
      receivers: [jaeger, opencensus]
      processors: [batch]
      #exporters: [jaeger]
    # metrics:
    #  receivers: [opencensus]
      #exporters: [exampleexporter]

extensions:
  health_check:
    port: 14269