receivers:
  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:
  opencensus:

processors:
  batch:
    timeout: 5s
    send_batch_size: 128   
  resource:
    attributes:
    - key: service.instance.id
      action: upsert
      value: ${K8S_POD_NAME}
    - key: k8s.pod.name
      action: upsert
      value: ${K8S_POD_NAME}
    - key: k8s.pod.uid
      action: upsert
      value: ${K8S_POD_UID}
    - key: k8s.namespace.name
      action: upsert
      value: ${K8S_NAMESPACE_NAME}
    - key: k8s.pod.ip
      action: upsert
      value: ${K8S_POD_IP}
    - key: k8s.cluster.name
      action: upsert
      value: ${K8S_CLUSTER_NAME}
    - key: host.name
      action: upsert
      value: ${HOST_NAME}
    - key: host.ip
      action: upsert
      value: ${HOST_IP}
    - key: cloud.provider
      action: upsert
      value: gcp
    - key: cloud.region
      action: upsert
      value: europe-west1



exporters:
  jaeger:
    endpoint: jaeger-collector.monitoring.svc.cluster.local:14250

service:
  pipelines:
    traces:
      receivers: [jaeger, opencensus]
      processors: [batch, resource]
      exporters: [jaeger]
