apiVersion: v1
kind: ConfigMap
metadata:
  name: linkerd-collector-config
  namespace: linkerd
  labels:
    linkerd.io/control-plane-component: linkerd-collector
    linkerd.io/control-plane-ns: linkerd
  annotations:
    linkerd.io/created-by: linkerd/cli stable-2.8.1
data:
  linkerd-collector-config: |
    receivers:
      opencensus:
        port: 55678
      zipkin:
        port: 9411
    queued-exporters:
      jaeger-all-in-one:
        num-workers: 4
        queue-size: 100
        retry-on-failure: true
        sender-type: jaeger-thrift-http
        jaeger-thrift-http:
          collector-endpoint: http://jaeger-collector.monitoring.svc.cluster.local:14268/api/traces
          timeout: 5s
