apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-ingester
  labels:
    component: jaeger
    app.kubernetes.io/component: ingester
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/name: jaeger-ingester
    app.kubernetes.io/part-of: jaeger
spec:
  selector:
    matchLabels:
      component: jaeger
      app.kubernetes.io/component: ingester
      app.kubernetes.io/instance: jaeger
      app.kubernetes.io/name: jaeger-ingester
      app.kubernetes.io/part-of: jaeger
  template:
    metadata:
      labels:
        component: jaeger
        app.kubernetes.io/component: ingester
        app.kubernetes.io/instance: jaeger
        app.kubernetes.io/name: jaeger-ingester
        app.kubernetes.io/part-of: jaeger
      annotations:
        linkerd.io/inject: disabled
        prometheus.io/port: "14270"
        prometheus.io/scrape: "true"
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: jaeger
      containers:
      - name: jaeger-ingester
        image: jaegertracing/jaeger-ingester:1.18
        ports:
        - containerPort: 14270
          name: admin-http
        env:
        - name: SPAN_STORAGE_TYPE
          value: elasticsearch
        envFrom:
        - secretRef:
            name: elasticsearch-auth
        args: [
          --es.server-urls=http://$(ELASTICSEARCH_SVC):9200,
          --ingester.deadlockInterval=0,
          --ingester.parallelism=1000,
          --kafka.consumer.brokers=$(KAFKA_BOOTSTRAP_SVC):9092,
          #--kafka.consumer.encoding=json,
          --kafka.consumer.group-id=jaeger-ingester,
          --kafka.consumer.topic=jaeger-spans,
        ]
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 14270
          initialDelaySeconds: 5
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 14270
          initialDelaySeconds: 1
        securityContext:
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsUser: 65532
          runAsGroup: 65532
          runAsNonRoot: true
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
