apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j

spec:
  selector:
    matchLabels:
      component: neo4j
  replicas: 1
  template:
    metadata:
      labels:
        component: neo4j
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: pull-plugins
        image: appropriate/curl:latest
        volumeMounts:
        - name: neo4j-plugins-volume
          mountPath: /plugins
        command:
        - "/bin/sh"
        - "-c"
        - |
          curl -sSL https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/3.5.0.7/apoc-3.5.0.7-all.jar > "/plugins/apoc-3.5.0.7-all.jar";
      containers:
      - name: neo4j
        image: neo4j:3.5
        imagePullPolicy: Always
        ports:
        - name: http-web
          containerPort: 7474
        - name: tcp-bolt
          containerPort: 7687
        volumeMounts:
        - name: neo4j-data-volume
          mountPath: /data
        - name: neo4j-logs-volume
          mountPath: /logs
        - name: neo4j-plugins-volume
          mountPath: /plugins
        env:
        - name: NEO4J_AUTH
          valueFrom:
            secretKeyRef:
              name: neo4j-env
              key: NEO4J_AUTH
        - name: ADVERTISED_HOST
          valueFrom:
            secretKeyRef:
              name: neo4j-env
              key: ADVERTISED_HOST
        - name: NEO4J_apoc_ttl_enabled
          value: "true"
        # - name: NEO4J_dbms_default__listen__address
        #   value: '0.0.0.0'
        - name: NEO4J_dbms_security_procedures_unrestricted
          value: algo.*,apoc.*
        # - name: NEO4J_dbms_ssl_policy_bolt_enabled
        #   value: 'false'
        - name: NEO4J_dbms_connector_bolt_tls__level
          value: OPTIONAL
        - name: NEO4J_dbms_connector_bolt_listen__address
          value: 0.0.0.0:7687
        - name: NEO4J_dbms_connector_http_listen__address
          value: 0.0.0.0:7474
        - name: NEO4J_dbms_allow__upgrade
          value: 'true'
        readinessProbe:
          tcpSocket:
            port: 7687
          initialDelaySeconds: 30
          periodSeconds: 3
        livenessProbe:
          initialDelaySeconds: 60
          tcpSocket:
            port: 7687
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "2Gi"
      volumes:
      - name: neo4j-data-volume
        emptyDir: {}
      - name: neo4j-logs-volume
        emptyDir: {}
      - name: neo4j-plugins-volume
        emptyDir: {}
