apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-all-in-one
  labels:
    component: jaeger
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/name: jaeger-all-in-one
    app.kubernetes.io/part-of: jaeger
  annotations:
    sidecar.istio.io/inject: "false"
    linkerd.io/inject: disabled
    prometheus.io/port: "14269"
    prometheus.io/scrape: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      component: jaeger
      app.kubernetes.io/component: all-in-one
      app.kubernetes.io/instance: jaeger
      app.kubernetes.io/name: jaeger-all-in-one
      app.kubernetes.io/part-of: jaeger
  template:
    metadata:
      labels:
        component: jaeger
        app.kubernetes.io/component: all-in-one
        app.kubernetes.io/instance: jaeger
        app.kubernetes.io/name: jaeger-all-in-one
        app.kubernetes.io/part-of: jaeger
      annotations:
        sidecar.istio.io/inject: "false"
        linkerd.io/inject: disabled
        prometheus.io/port: "14269"
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: jaeger
      securityContext:
        fsGroup: 65532
      containers:
      - name: jaeger-all-in-one
        image: jaegertracing/all-in-one:1.18
        ports:
        - containerPort: 5775
          name: zk-compact-trft
          protocol: UDP
        - containerPort: 5778
          name: config-rest
        - containerPort: 6831
          name: jg-compact-trft
          protocol: UDP
        - containerPort: 6832
          name: jg-binary-trft
          protocol: UDP
        - containerPort: 9411
          name: zipkin
        - containerPort: 14267
          name: c-tchan-trft
        - containerPort: 14268
          name: c-binary-trft
        - containerPort: 16686
          name: query
        - containerPort: 14269
          name: admin-http
        - containerPort: 14250
          name: grpc
        volumeMounts:
        - mountPath: /etc/config/ui.json
          name: jaeger-ui-configuration-volume
          subPath: ui.json
          readOnly: true
        - mountPath: /etc/jaeger/sampling/sampling.json
          name: jaeger-sampling-configuration-volume
          subPath: sampling.json
          readOnly: true
        env:
        - name: SPAN_STORAGE_TYPE
          value: memory
        - name: ADMIN_HTTP_HOST_PORT
          value: :14269
        - name: COLLECTOR_GRPC_SERVER_HOST_PORT
          value: :14250
        - name: COLLECTOR_HTTP_SERVER_HOST_PORT
          value: :14268
        - name: COLLECTOR_ZIPKIN_HOST_PORT
          value: :9411
        - name: SAMPLING_STRATEGIES_FILE
          value: /etc/jaeger/sampling/sampling.json
        - name: PROCESSOR_JAEGER_BINARY_SERVER_HOST_PORT
          value: :6832
        - name: PROCESSOR_JAEGER_COMPACT_SERVER_HOST_PORT
          value: :6831
        - name: QUERY_HOST_PORT
          value: :16686
        - name: QUERY_BASE_PATH
          value: /jaeger
        - name: QUERY_UI_CONFIG
          value: /etc/config/ui.json
        - name: MEMORY_MAX_TRACES
          value: "10000"
        args: [
          --log-level=debug,
        ]
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 14269
          initialDelaySeconds: 5
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 14269
          initialDelaySeconds: 1
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsUser: 65532
          runAsGroup: 65532
          runAsNonRoot: true
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 4Gi
      volumes:
      - name: jaeger-ui-configuration-volume
        configMap:
          name: jaeger-ui-config
      - name: jaeger-sampling-configuration-volume
        configMap:
          name: jaeger-sampling-config
