---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
spec:
  selector:
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/name: jaeger-all-in-one


---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector-headless
spec:
  selector:
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/name: jaeger-all-in-one


---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
spec:
  selector:
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/name: jaeger-all-in-one
