apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  labels:
    component: jaeger
    app.kubernetes.io/component: service-collector
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/name: jaeger-collector
    app.kubernetes.io/part-of: jaeger
spec:
  selector:
    component: jaeger
    app.kubernetes.io/component: collector
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/name: jaeger-collector
    app.kubernetes.io/part-of: jaeger
  ports:
  - name: http-zipkin
    port: 9411
  - name: http-grpc
    port: 14250
  - name: c-tchan-trft
    port: 14267
  - name: http-c-binary-trft
    port: 14268
