apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: node-exporter
  name: node-exporter
spec:
  clusterIP: None
  selector:
    app: node-exporter
  ports:
  - name: https
    port: 9100
    targetPort: https
